// Mocks generated by Mockito 5.4.0 from annotations
// in challenge/test/widget_test/view/first_tab_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:challenge/src/core/resource/data_state.dart' as _i5;
import 'package:challenge/src/core/use_case/use_case_interface.dart' as _i2;
import 'package:challenge/src/domain/entity/person/persons_list_entity.dart'
    as _i6;
import 'package:challenge/src/presentation/bloc/person_bloc.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUseCaseInterface_0<T> extends _i1.SmartFake
    implements _i2.UseCaseInterface<T> {
  _FakeUseCaseInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersonBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonBloc extends _i1.Mock implements _i3.PersonBloc {
  MockPersonBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UseCaseInterface<dynamic> get useCaseInterface => (super.noSuchMethod(
        Invocation.getter(#useCaseInterface),
        returnValue: _FakeUseCaseInterface_0<dynamic>(
          this,
          Invocation.getter(#useCaseInterface),
        ),
      ) as _i2.UseCaseInterface<dynamic>);

  @override
  _i4.Stream<_i5.DataState<_i6.PersonsListEntity>> get personsListStream =>
      (super.noSuchMethod(
        Invocation.getter(#personsListStream),
        returnValue: _i4.Stream<_i5.DataState<_i6.PersonsListEntity>>.empty(),
      ) as _i4.Stream<_i5.DataState<_i6.PersonsListEntity>>);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void getPersonsList() => super.noSuchMethod(
        Invocation.method(
          #getPersonsList,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
